import 'dotenv/config';
import mongoose from 'mongoose';
import Product from './models/Product';

const MONGODB_URI =
  process.env.MONGODB_URI ||
  'mongodb+srv://ankitkhatri:DmH21gLy2ttyZfhJ@khatrisoftware.x33xsgo.mongodb.net/fashionZone?retryWrites=true&w=majority';

const products = [
  // ─── WOMEN - DRESSES ──────────────────────────────────────────────────────
  {
    name: 'Floral Wrap Midi Dress',
    description:
      'A stunning floral wrap midi dress perfect for every occasion. Crafted from soft chiffon fabric with a flattering V-neckline and adjustable tie waist. The vibrant floral print adds a touch of elegance and femininity. Perfect for brunches, garden parties, and summer evenings.',
    category: 'women',
    subcategory: 'dresses',
    images: [
      'https://images.unsplash.com/photo-1595777457583-95e059d581b8?w=600',
      'https://images.unsplash.com/photo-1572804013309-59a88b7e92f1?w=600',
    ],
    sizes: ['XS', 'S', 'M', 'L', 'XL'],
    colors: ['Floral Pink', 'Floral Blue', 'Floral Yellow'],
    originalPrice: 2999,
    price: 1799,
    discount: 40,
    stock: 45,
    tags: ['dress', 'floral', 'midi', 'wrap', 'summer', 'party', 'women'],
    rating: 4.7,
    reviewCount: 238,
    featured: true,
    isNew: false,
    brand: 'Zara',
    material: '100% Chiffon',
    careInstructions: 'Hand wash cold, do not tumble dry, iron on low heat',
  },
  {
    name: 'Elegant Evening Gown',
    description:
      'A timeless floor-length evening gown that exudes sophistication. Features a fitted bodice, sweetheart neckline, and flowing A-line skirt. Adorned with subtle sequin detailing at the waist. Ideal for galas, weddings, and formal celebrations.',
    category: 'women',
    subcategory: 'dresses',
    images: [
      'https://images.unsplash.com/photo-1596783074918-c84cb06531ca?w=600',
      'https://images.unsplash.com/photo-1572804013309-59a88b7e92f1?w=600',
    ],
    sizes: ['XS', 'S', 'M', 'L', 'XL', 'XXL'],
    colors: ['Navy Blue', 'Burgundy', 'Emerald Green', 'Black'],
    originalPrice: 7999,
    price: 4799,
    discount: 40,
    stock: 20,
    tags: ['gown', 'evening', 'formal', 'party', 'wedding', 'women', 'elegant'],
    rating: 4.9,
    reviewCount: 145,
    featured: true,
    isNew: true,
    brand: 'Mango',
    material: '95% Polyester, 5% Spandex',
    careInstructions: 'Dry clean only',
  },
  {
    name: 'Boho Sundress with Tassels',
    description:
      'A free-spirited bohemian sundress featuring tassel hem detailing and adjustable spaghetti straps. Made from lightweight cotton blend fabric with a beautiful tie-dye pattern. Perfect for beach days, festivals, and casual summer outings.',
    category: 'women',
    subcategory: 'dresses',
    images: [
      'https://images.unsplash.com/photo-1595777457583-95e059d581b8?w=600',
      'https://images.unsplash.com/photo-1596783074918-c84cb06531ca?w=600',
    ],
    sizes: ['XS', 'S', 'M', 'L', 'XL'],
    colors: ['Tie-dye Blue', 'Tie-dye Pink', 'Earthy Rust'],
    originalPrice: 1999,
    price: 1199,
    discount: 40,
    stock: 60,
    tags: ['boho', 'sundress', 'tassel', 'beach', 'summer', 'casual', 'women'],
    rating: 4.5,
    reviewCount: 312,
    featured: false,
    isNew: true,
    brand: 'FabIndia',
    material: '60% Cotton, 40% Viscose',
    careInstructions: 'Machine wash cold, gentle cycle, lay flat to dry',
  },

  // ─── WOMEN - ETHNIC ────────────────────────────────────────────────────────
  {
    name: 'Banarasi Silk Saree',
    description:
      'A magnificent Banarasi silk saree woven with intricate gold zari work. Features a heavy border with traditional motifs and a richly embroidered pallu. This heirloom-quality saree is a timeless piece that celebrates India\'s rich textile heritage. Perfect for weddings and festive occasions.',
    category: 'women',
    subcategory: 'ethnic',
    images: [
      'https://images.unsplash.com/photo-1610030469983-98e550d6193c?w=600',
      'https://images.unsplash.com/photo-1617627143750-d86bc21e42bb?w=600',
    ],
    sizes: ['Free Size'],
    colors: ['Royal Red', 'Deep Maroon', 'Peacock Blue', 'Forest Green'],
    originalPrice: 12999,
    price: 8999,
    discount: 31,
    stock: 15,
    tags: ['saree', 'banarasi', 'silk', 'ethnic', 'wedding', 'festive', 'traditional', 'women'],
    rating: 4.9,
    reviewCount: 189,
    featured: true,
    isNew: false,
    brand: 'Nalli Silks',
    material: '100% Pure Banarasi Silk',
    careInstructions: 'Dry clean only, store in muslin cloth',
  },
  {
    name: 'Anarkali Embroidered Suit',
    description:
      'A regal Anarkali suit adorned with delicate thread embroidery and mirror work. Comes complete with matching churidar pants and dupatta. The floor-length flared kurta creates a graceful silhouette. Perfect for Eid, Diwali, and festive celebrations.',
    category: 'women',
    subcategory: 'ethnic',
    images: [
      'https://images.unsplash.com/photo-1617627143750-d86bc21e42bb?w=600',
      'https://images.unsplash.com/photo-1610030469983-98e550d6193c?w=600',
    ],
    sizes: ['XS', 'S', 'M', 'L', 'XL', 'XXL'],
    colors: ['Mint Green', 'Peach', 'Lavender', 'Sky Blue'],
    originalPrice: 5999,
    price: 3599,
    discount: 40,
    stock: 30,
    tags: ['anarkali', 'suit', 'embroidered', 'ethnic', 'festive', 'traditional', 'women', 'kurta'],
    rating: 4.7,
    reviewCount: 203,
    featured: true,
    isNew: true,
    brand: 'Biba',
    material: 'Georgette with silk lining',
    careInstructions: 'Dry clean recommended, hand wash in cold water if necessary',
  },
  {
    name: 'Cotton Printed Kurti',
    description:
      'A comfortable and stylish cotton kurti with a vibrant block print pattern. Features a round neck, three-quarter sleeves, and side slits for easy movement. Perfect for everyday wear, office, or casual outings paired with jeans or palazzo pants.',
    category: 'women',
    subcategory: 'ethnic',
    images: [
      'https://images.unsplash.com/photo-1610030469983-98e550d6193c?w=600',
      'https://images.unsplash.com/photo-1434389677669-e08b4cac3105?w=600',
    ],
    sizes: ['XS', 'S', 'M', 'L', 'XL', 'XXL', '3XL'],
    colors: ['Indigo Blue', 'Terracotta', 'Sage Green', 'Dusty Pink'],
    originalPrice: 1299,
    price: 799,
    discount: 38,
    stock: 80,
    tags: ['kurti', 'cotton', 'printed', 'block print', 'ethnic', 'casual', 'women', 'everyday'],
    rating: 4.4,
    reviewCount: 567,
    featured: false,
    isNew: false,
    brand: 'W for Woman',
    material: '100% Cotton',
    careInstructions: 'Machine washable, wash with similar colors',
  },

  // ─── WOMEN - TOPS ─────────────────────────────────────────────────────────
  {
    name: 'Ruffled Floral Blouse',
    description:
      'A charming ruffled blouse with an all-over floral print and flared sleeves. Made from lightweight georgette fabric, it drapes beautifully and feels comfortable all day. The romantic aesthetic makes it perfect for date nights and brunch outings.',
    category: 'women',
    subcategory: 'tops',
    images: [
      'https://images.unsplash.com/photo-1434389677669-e08b4cac3105?w=600',
      'https://images.unsplash.com/photo-1485218126466-34e6392ec754?w=600',
    ],
    sizes: ['XS', 'S', 'M', 'L', 'XL'],
    colors: ['Floral White', 'Floral Peach', 'Floral Navy'],
    originalPrice: 1799,
    price: 999,
    discount: 44,
    stock: 55,
    tags: ['blouse', 'ruffle', 'floral', 'top', 'women', 'casual', 'romantic'],
    rating: 4.6,
    reviewCount: 178,
    featured: false,
    isNew: true,
    brand: 'H&M',
    material: '100% Georgette',
    careInstructions: 'Hand wash cold or dry clean',
  },
  {
    name: 'Classic White Linen Shirt',
    description:
      'A crisp white linen shirt that is a wardrobe essential. Features a button-down front, relaxed fit, and roll-up sleeves with button tabs. Breathable and comfortable, it transitions seamlessly from workwear to weekend casual. Pair it with everything from jeans to trousers.',
    category: 'women',
    subcategory: 'tops',
    images: [
      'https://images.unsplash.com/photo-1485218126466-34e6392ec754?w=600',
      'https://images.unsplash.com/photo-1434389677669-e08b4cac3105?w=600',
    ],
    sizes: ['XS', 'S', 'M', 'L', 'XL', 'XXL'],
    colors: ['White', 'Off-White', 'Pale Blue', 'Light Pink'],
    originalPrice: 2499,
    price: 1499,
    discount: 40,
    stock: 70,
    tags: ['shirt', 'linen', 'white', 'casual', 'office', 'women', 'classic', 'wardrobe essential'],
    rating: 4.5,
    reviewCount: 289,
    featured: false,
    isNew: false,
    brand: 'Marks & Spencer',
    material: '100% Linen',
    careInstructions: 'Machine wash warm, iron while slightly damp',
  },

  // ─── WOMEN - BOTTOMS ───────────────────────────────────────────────────────
  {
    name: 'High-Waist Palazzo Pants',
    description:
      'Elegant wide-leg palazzo pants with a high-waist design for a flattering silhouette. Made from fluid crepe fabric that flows beautifully with every step. Features an elastic waistband and pockets. Perfect for both casual and semi-formal occasions.',
    category: 'women',
    subcategory: 'bottoms',
    images: [
      'https://images.unsplash.com/photo-1572804013309-59a88b7e92f1?w=600',
      'https://images.unsplash.com/photo-1595777457583-95e059d581b8?w=600',
    ],
    sizes: ['XS', 'S', 'M', 'L', 'XL', 'XXL'],
    colors: ['Black', 'Navy', 'Olive', 'Beige', 'Maroon'],
    originalPrice: 1999,
    price: 1199,
    discount: 40,
    stock: 65,
    tags: ['palazzo', 'pants', 'wide-leg', 'high-waist', 'women', 'casual', 'comfortable'],
    rating: 4.6,
    reviewCount: 341,
    featured: false,
    isNew: false,
    brand: 'Global Desi',
    material: '100% Crepe',
    careInstructions: 'Machine wash cold, gentle cycle',
  },

  // ─── MEN - WESTERN ─────────────────────────────────────────────────────────
  {
    name: 'Classic Slim-Fit Chinos',
    description:
      'Premium slim-fit chinos crafted from stretch cotton twill for all-day comfort. Features a mid-rise waist, flat front, and tapered leg. Versatile enough for office wear with a blazer or weekend casual with a polo. A modern wardrobe staple for the style-conscious man.',
    category: 'men',
    subcategory: 'bottoms',
    images: [
      'https://images.unsplash.com/photo-1617137968427-85924c800a22?w=600',
      'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=600',
    ],
    sizes: ['28', '30', '32', '34', '36', '38', '40'],
    colors: ['Khaki', 'Navy', 'Olive', 'Stone', 'Black'],
    originalPrice: 2999,
    price: 1799,
    discount: 40,
    stock: 90,
    tags: ['chinos', 'pants', 'slim-fit', 'men', 'casual', 'office', 'trousers'],
    rating: 4.6,
    reviewCount: 412,
    featured: true,
    isNew: false,
    brand: 'Jack & Jones',
    material: '98% Cotton, 2% Elastane',
    careInstructions: 'Machine wash at 30°C, do not bleach',
  },
  {
    name: 'Oxford Button-Down Shirt',
    description:
      'A timeless Oxford button-down shirt made from premium 100% cotton Oxford fabric. Features a classic button-down collar, chest pocket, and tailored fit. The fine weave gives it a subtle texture that elevates any outfit. Ideal for business casual and smart casual occasions.',
    category: 'men',
    subcategory: 'tops',
    images: [
      'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=600',
      'https://images.unsplash.com/photo-1617137968427-85924c800a22?w=600',
    ],
    sizes: ['S', 'M', 'L', 'XL', 'XXL', '3XL'],
    colors: ['White', 'Light Blue', 'Pink', 'Lavender', 'Mint'],
    originalPrice: 2499,
    price: 1499,
    discount: 40,
    stock: 75,
    tags: ['shirt', 'oxford', 'button-down', 'men', 'office', 'formal', 'classic'],
    rating: 4.7,
    reviewCount: 356,
    featured: true,
    isNew: false,
    brand: 'Van Heusen',
    material: '100% Cotton Oxford weave',
    careInstructions: 'Machine wash warm, iron medium heat',
  },
  {
    name: 'Slim-Fit Denim Jeans',
    description:
      'Modern slim-fit jeans in classic medium-wash denim with subtle whiskering and fading. Made from stretch denim for maximum comfort and mobility. Features five pockets, a mid-rise waist, and a tapered leg that ends perfectly at the ankle. The essential pair every wardrobe needs.',
    category: 'men',
    subcategory: 'bottoms',
    images: [
      'https://images.unsplash.com/photo-1617137968427-85924c800a22?w=600',
      'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=600',
    ],
    sizes: ['28', '30', '32', '34', '36', '38'],
    colors: ['Medium Blue', 'Dark Blue', 'Black', 'Light Blue'],
    originalPrice: 3499,
    price: 1999,
    discount: 43,
    stock: 100,
    tags: ['jeans', 'denim', 'slim-fit', 'men', 'casual', 'everyday', 'denim'],
    rating: 4.5,
    reviewCount: 521,
    featured: false,
    isNew: false,
    brand: "Levi's",
    material: '99% Cotton, 1% Elastane',
    careInstructions: 'Machine wash inside out, cold water, hang dry',
  },
  {
    name: 'Premium Crew-Neck Sweatshirt',
    description:
      'A luxuriously soft crew-neck sweatshirt made from a premium cotton-polyester fleece blend. Features a relaxed fit, ribbed cuffs and hem, and a kangaroo pocket. The heavyweight fabric provides warmth without bulk. Perfect for layering in cooler months or lounging on weekends.',
    category: 'men',
    subcategory: 'tops',
    images: [
      'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=600',
      'https://images.unsplash.com/photo-1617137968427-85924c800a22?w=600',
    ],
    sizes: ['S', 'M', 'L', 'XL', 'XXL'],
    colors: ['Charcoal', 'Navy', 'Forest Green', 'Maroon', 'Heather Grey'],
    originalPrice: 2499,
    price: 1499,
    discount: 40,
    stock: 60,
    tags: ['sweatshirt', 'crew-neck', 'men', 'casual', 'winter', 'fleece', 'comfortable'],
    rating: 4.8,
    reviewCount: 298,
    featured: false,
    isNew: true,
    brand: 'Puma',
    material: '70% Cotton, 30% Polyester fleece',
    careInstructions: 'Machine wash warm, tumble dry low',
  },

  // ─── MEN - ETHNIC ──────────────────────────────────────────────────────────
  {
    name: 'Embroidered Kurta Pajama Set',
    description:
      'An exquisite kurta pajama set featuring intricate thread embroidery along the neckline and placket. Made from premium cotton fabric that is comfortable for long hours of wear. The straight-cut kurta comes with matching straight-leg pajama. A sophisticated choice for festivals and family gatherings.',
    category: 'men',
    subcategory: 'ethnic',
    images: [
      'https://images.unsplash.com/photo-1617137968427-85924c800a22?w=600',
      'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=600',
    ],
    sizes: ['S', 'M', 'L', 'XL', 'XXL', '3XL'],
    colors: ['Off-White', 'Cream', 'Light Blue', 'Sage Green'],
    originalPrice: 3999,
    price: 2399,
    discount: 40,
    stock: 35,
    tags: ['kurta', 'pajama', 'ethnic', 'men', 'festive', 'traditional', 'embroidered'],
    rating: 4.7,
    reviewCount: 187,
    featured: true,
    isNew: true,
    brand: 'Manyavar',
    material: '100% Cotton',
    careInstructions: 'Hand wash or machine wash on delicate, dry in shade',
  },
  {
    name: 'Nehru Collar Bandhgala Jacket',
    description:
      'A sophisticated Nehru collar bandhgala jacket crafted from premium wool-blend fabric. Features a structured cut, five-button front closure, and hand-stitched detailing. The timeless design works beautifully over a kurta for festivals or a shirt for cocktail events.',
    category: 'men',
    subcategory: 'ethnic',
    images: [
      'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=600',
      'https://images.unsplash.com/photo-1617137968427-85924c800a22?w=600',
    ],
    sizes: ['S', 'M', 'L', 'XL', 'XXL'],
    colors: ['Black', 'Navy', 'Ivory', 'Deep Burgundy'],
    originalPrice: 6999,
    price: 4199,
    discount: 40,
    stock: 25,
    tags: ['bandhgala', 'nehru', 'jacket', 'men', 'ethnic', 'formal', 'wedding', 'celebration'],
    rating: 4.9,
    reviewCount: 134,
    featured: true,
    isNew: false,
    brand: 'Manyavar',
    material: '80% Wool, 20% Polyester',
    careInstructions: 'Dry clean only',
  },

  // ─── KIDS ──────────────────────────────────────────────────────────────────
  {
    name: "Girls' Princess Tutu Dress",
    description:
      'A magical princess-inspired tutu dress that every little girl will adore. Features a sparkling sequin bodice, multilayer tulle skirt, and a big satin bow at the back. The soft lining ensures comfort during play. Perfect for birthdays, parties, and special occasions.',
    category: 'kids',
    subcategory: 'dresses',
    images: [
      'https://images.unsplash.com/photo-1596783074918-c84cb06531ca?w=600',
      'https://images.unsplash.com/photo-1595777457583-95e059d581b8?w=600',
    ],
    sizes: ['2-3Y', '3-4Y', '4-5Y', '5-6Y', '6-7Y', '7-8Y'],
    colors: ['Princess Pink', 'Lavender', 'Mint', 'Golden Yellow'],
    originalPrice: 1999,
    price: 1199,
    discount: 40,
    stock: 40,
    tags: ['dress', 'tutu', 'princess', 'kids', 'girls', 'birthday', 'party', 'sequin'],
    rating: 4.8,
    reviewCount: 267,
    featured: true,
    isNew: true,
    brand: 'H&M Kids',
    material: 'Sequin bodice, Tulle skirt, Cotton lining',
    careInstructions: 'Hand wash cold, do not tumble dry',
  },
  {
    name: "Boys' Casual Cargo Shorts",
    description:
      'Durable and practical cargo shorts for active boys. Features multiple pockets including two cargo pockets on the sides, an elastic waist with drawstring for the perfect fit, and a reinforced seat for extra durability during play. Made from easy-care cotton blend fabric.',
    category: 'kids',
    subcategory: 'bottoms',
    images: [
      'https://images.unsplash.com/photo-1617137968427-85924c800a22?w=600',
      'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=600',
    ],
    sizes: ['3-4Y', '4-5Y', '5-6Y', '6-7Y', '7-8Y', '8-9Y', '9-10Y'],
    colors: ['Khaki', 'Navy', 'Olive', 'Grey'],
    originalPrice: 999,
    price: 599,
    discount: 40,
    stock: 55,
    tags: ['shorts', 'cargo', 'boys', 'kids', 'casual', 'play', 'comfortable'],
    rating: 4.5,
    reviewCount: 189,
    featured: false,
    isNew: false,
    brand: 'HRX by Hrithik Roshan',
    material: '60% Cotton, 40% Polyester',
    careInstructions: 'Machine wash warm',
  },
  {
    name: "Kids' Traditional Lehenga Choli",
    description:
      'An adorable traditional lehenga choli set for girls that captures the essence of Indian festive fashion. Features a beautifully embroidered blouse, flared lehenga skirt with printed border, and a matching dupatta. Soft fabric ensures comfort throughout the day.',
    category: 'kids',
    subcategory: 'ethnic',
    images: [
      'https://images.unsplash.com/photo-1610030469983-98e550d6193c?w=600',
      'https://images.unsplash.com/photo-1617627143750-d86bc21e42bb?w=600',
    ],
    sizes: ['2-3Y', '3-4Y', '4-5Y', '5-6Y', '6-7Y', '7-8Y', '8-9Y'],
    colors: ['Hot Pink', 'Royal Blue', 'Coral Orange', 'Lime Green'],
    originalPrice: 1799,
    price: 1099,
    discount: 39,
    stock: 30,
    tags: ['lehenga', 'choli', 'kids', 'girls', 'ethnic', 'festive', 'traditional', 'Diwali', 'Navratri'],
    rating: 4.8,
    reviewCount: 214,
    featured: true,
    isNew: true,
    brand: 'Biba Girls',
    material: 'Georgette with cotton lining',
    careInstructions: 'Hand wash cold, dry in shade',
  },
  {
    name: "Kids' Graphic Print T-Shirt Pack",
    description:
      'A fun pack of three graphic print t-shirts for kids who love to express themselves. Each t-shirt features a different vibrant print — superhero, dinosaur, and space-themed. Made from soft 100% cotton that is gentle on sensitive skin and keeps kids comfortable through play.',
    category: 'kids',
    subcategory: 'tops',
    images: [
      'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=600',
      'https://images.unsplash.com/photo-1617137968427-85924c800a22?w=600',
    ],
    sizes: ['2-3Y', '3-4Y', '4-5Y', '5-6Y', '6-7Y', '7-8Y', '8-9Y', '10-11Y'],
    colors: ['Multicolour Pack'],
    originalPrice: 1499,
    price: 899,
    discount: 40,
    stock: 70,
    tags: ['t-shirt', 'graphic', 'kids', 'boys', 'casual', 'pack', 'comfortable', 'cotton'],
    rating: 4.6,
    reviewCount: 378,
    featured: false,
    isNew: true,
    brand: 'Allen Solly Junior',
    material: '100% Combed Cotton',
    careInstructions: 'Machine wash cold, tumble dry low',
  },

  // ─── ACCESSORIES - BAGS ────────────────────────────────────────────────────
  {
    name: 'Structured Leather Tote Bag',
    description:
      'A sleek structured tote bag crafted from premium vegan leather with a minimalist aesthetic. Features a spacious main compartment with a zip closure, internal pockets, and a detachable pouch. The polished gold-tone hardware and clean lines make it perfect for office and travel.',
    category: 'accessories',
    subcategory: 'bags',
    images: [
      'https://images.unsplash.com/photo-1548036328-c9fa89d128fa?w=600',
      'https://images.unsplash.com/photo-1523275335684-37898b6baf30?w=600',
    ],
    sizes: ['One Size'],
    colors: ['Black', 'Tan', 'Nude', 'White'],
    originalPrice: 4999,
    price: 2999,
    discount: 40,
    stock: 25,
    tags: ['bag', 'tote', 'leather', 'accessories', 'women', 'office', 'structured', 'handbag'],
    rating: 4.7,
    reviewCount: 156,
    featured: true,
    isNew: false,
    brand: 'Caprese',
    material: 'Premium Vegan Leather, Polyester lining',
    careInstructions: 'Wipe with a damp cloth, use leather conditioner occasionally',
  },
  {
    name: 'Crossbody Quilted Chain Bag',
    description:
      'A chic quilted crossbody bag with an iconic chain strap. Features classic diamond quilting, a zip-top closure, and an interior slip pocket. The adjustable chain strap can be worn cross-body or over the shoulder. Adds instant elegance to any outfit.',
    category: 'accessories',
    subcategory: 'bags',
    images: [
      'https://images.unsplash.com/photo-1523275335684-37898b6baf30?w=600',
      'https://images.unsplash.com/photo-1548036328-c9fa89d128fa?w=600',
    ],
    sizes: ['One Size'],
    colors: ['Black', 'Blush Pink', 'Ivory', 'Camel'],
    originalPrice: 3499,
    price: 2099,
    discount: 40,
    stock: 30,
    tags: ['bag', 'crossbody', 'quilted', 'chain', 'accessories', 'women', 'elegant', 'handbag'],
    rating: 4.8,
    reviewCount: 234,
    featured: true,
    isNew: true,
    brand: 'Hidesign',
    material: 'PU leather with gold-tone chain strap',
    careInstructions: 'Wipe clean with soft dry cloth',
  },
  {
    name: 'Canvas Backpack with Laptop Sleeve',
    description:
      'A practical and stylish canvas backpack designed for the modern professional. Features a padded 15" laptop sleeve, multiple organized compartments, a front zip pocket, and padded adjustable straps. The water-resistant canvas material keeps your belongings safe in light rain.',
    category: 'accessories',
    subcategory: 'bags',
    images: [
      'https://images.unsplash.com/photo-1548036328-c9fa89d128fa?w=600',
      'https://images.unsplash.com/photo-1523275335684-37898b6baf30?w=600',
    ],
    sizes: ['One Size'],
    colors: ['Charcoal', 'Navy', 'Olive', 'Black'],
    originalPrice: 2999,
    price: 1799,
    discount: 40,
    stock: 40,
    tags: ['backpack', 'canvas', 'laptop', 'men', 'women', 'work', 'travel', 'accessories'],
    rating: 4.6,
    reviewCount: 345,
    featured: false,
    isNew: false,
    brand: 'Wildcraft',
    material: 'Water-resistant Canvas, Polyester lining',
    careInstructions: 'Spot clean with damp cloth, air dry',
  },

  // ─── ACCESSORIES - JEWELRY ─────────────────────────────────────────────────
  {
    name: 'Kundan Meenakari Earrings',
    description:
      'Exquisite Kundan Meenakari earrings featuring hand-set kundan stones and intricate enamel meenakari work in vibrant colors. These long dangling earrings are inspired by Rajasthani craft traditions. Perfect for weddings, festivals, and ethnic wear occasions.',
    category: 'accessories',
    subcategory: 'jewelry',
    images: [
      'https://images.unsplash.com/photo-1523275335684-37898b6baf30?w=600',
      'https://images.unsplash.com/photo-1548036328-c9fa89d128fa?w=600',
    ],
    sizes: ['One Size'],
    colors: ['Gold with Red', 'Gold with Green', 'Gold with Blue', 'Gold with Multi'],
    originalPrice: 1499,
    price: 899,
    discount: 40,
    stock: 50,
    tags: ['earrings', 'kundan', 'meenakari', 'jewelry', 'ethnic', 'women', 'festive', 'traditional'],
    rating: 4.7,
    reviewCount: 189,
    featured: false,
    isNew: false,
    brand: 'Zaveri Pearls',
    material: 'Brass base with Kundan stones and meenakari enamel',
    careInstructions: 'Avoid contact with water and perfumes, store in jewelry box',
  },
  {
    name: 'Layered Gold-Tone Necklace Set',
    description:
      'A contemporary layered necklace set that adds instant glamour to any outfit. Includes three chains of varying lengths — a delicate choker, a mid-length chain with a minimalist pendant, and a longer layering chain. The warm gold-tone finish is versatile with both casual and formal looks.',
    category: 'accessories',
    subcategory: 'jewelry',
    images: [
      'https://images.unsplash.com/photo-1548036328-c9fa89d128fa?w=600',
      'https://images.unsplash.com/photo-1523275335684-37898b6baf30?w=600',
    ],
    sizes: ['One Size'],
    colors: ['Gold', 'Silver', 'Rose Gold'],
    originalPrice: 999,
    price: 599,
    discount: 40,
    stock: 60,
    tags: ['necklace', 'layered', 'gold', 'jewelry', 'women', 'accessories', 'minimalist', 'everyday'],
    rating: 4.5,
    reviewCount: 312,
    featured: false,
    isNew: true,
    brand: 'Ayesha Accessories',
    material: 'Zinc alloy with gold plating',
    careInstructions: 'Keep away from moisture, store flat',
  },

  // ─── ACCESSORIES - FOOTWEAR ────────────────────────────────────────────────
  {
    name: 'Block Heel Ankle Strap Sandals',
    description:
      'Chic block heel sandals with an elegant ankle strap and square toe design. The comfortable 4-inch block heel provides stability without sacrificing style. Made from faux suede with a cushioned insole for all-day comfort. Perfect for office, dinners, and events.',
    category: 'accessories',
    subcategory: 'footwear',
    images: [
      'https://images.unsplash.com/photo-1543163521-1bf539c55dd2?w=600',
      'https://images.unsplash.com/photo-1542291026-7eec264c27ff?w=600',
    ],
    sizes: ['35', '36', '37', '38', '39', '40', '41'],
    colors: ['Black', 'Nude', 'Blush', 'Brown'],
    originalPrice: 3499,
    price: 2099,
    discount: 40,
    stock: 35,
    tags: ['sandals', 'block heel', 'ankle strap', 'women', 'footwear', 'office', 'heels'],
    rating: 4.6,
    reviewCount: 223,
    featured: true,
    isNew: false,
    brand: 'Steve Madden',
    material: 'Faux suede upper, rubber outsole',
    careInstructions: 'Wipe clean with dry cloth, store in dust bag',
  },
  {
    name: 'Classic White Leather Sneakers',
    description:
      'Timeless minimalist white sneakers crafted from premium leather with a clean profile and cushioned sole. Features a lace-up design, padded collar, and durable rubber outsole. The versatile style pairs perfectly with everything from jeans to dresses. A wardrobe staple that never goes out of style.',
    category: 'accessories',
    subcategory: 'footwear',
    images: [
      'https://images.unsplash.com/photo-1542291026-7eec264c27ff?w=600',
      'https://images.unsplash.com/photo-1543163521-1bf539c55dd2?w=600',
    ],
    sizes: ['36', '37', '38', '39', '40', '41', '42', '43', '44'],
    colors: ['White', 'White/Gum', 'All Black'],
    originalPrice: 4999,
    price: 2999,
    discount: 40,
    stock: 50,
    tags: ['sneakers', 'white', 'leather', 'footwear', 'casual', 'unisex', 'classic', 'minimalist'],
    rating: 4.8,
    reviewCount: 487,
    featured: true,
    isNew: false,
    brand: 'Veja',
    material: 'Premium leather upper, rubber outsole',
    careInstructions: 'Wipe with damp cloth, use sneaker protector spray',
  },
  {
    name: 'Kolhapuri Flat Chappals',
    description:
      'Authentic handcrafted Kolhapuri chappals made by skilled artisans from Maharashtra. Featuring intricate leather-work patterns and a durable double-layer sole, these traditional sandals are both beautiful and comfortable. The earthy tones complement ethnic and boho outfits perfectly.',
    category: 'accessories',
    subcategory: 'footwear',
    images: [
      'https://images.unsplash.com/photo-1543163521-1bf539c55dd2?w=600',
      'https://images.unsplash.com/photo-1542291026-7eec264c27ff?w=600',
    ],
    sizes: ['35', '36', '37', '38', '39', '40', '41'],
    colors: ['Tan', 'Brown', 'Black', 'Camel'],
    originalPrice: 1499,
    price: 899,
    discount: 40,
    stock: 45,
    tags: ['kolhapuri', 'chappals', 'sandals', 'traditional', 'ethnic', 'women', 'footwear', 'handcrafted'],
    rating: 4.7,
    reviewCount: 198,
    featured: false,
    isNew: false,
    brand: 'Jaipur Kala Kendra',
    material: 'Genuine leather',
    careInstructions: 'Apply leather conditioner regularly, avoid prolonged water exposure',
  },
  {
    name: "Men's Premium Oxford Shoes",
    description:
      'Sophisticated leather Oxford shoes for the discerning man. Crafted from full-grain leather with a Goodyear welt construction for unparalleled durability. Features a classic cap-toe design, perforated brogueing details, and a comfortable leather insole that molds to your foot over time.',
    category: 'accessories',
    subcategory: 'footwear',
    images: [
      'https://images.unsplash.com/photo-1542291026-7eec264c27ff?w=600',
      'https://images.unsplash.com/photo-1543163521-1bf539c55dd2?w=600',
    ],
    sizes: ['39', '40', '41', '42', '43', '44', '45'],
    colors: ['Tan', 'Dark Brown', 'Black', 'Burgundy'],
    originalPrice: 8999,
    price: 5399,
    discount: 40,
    stock: 20,
    tags: ['oxford', 'shoes', 'men', 'formal', 'leather', 'footwear', 'office', 'premium'],
    rating: 4.9,
    reviewCount: 112,
    featured: true,
    isNew: false,
    brand: 'Clarks',
    material: 'Full-grain leather upper, leather sole with rubber heel tap',
    careInstructions: 'Polish regularly, use cedar shoe trees, professional cleaning recommended',
  },

  // ─── WOMEN - WESTERN (additional) ──────────────────────────────────────────
  {
    name: 'Puff-Sleeve Mini Dress',
    description:
      'A playful and trendy mini dress featuring dramatic puff sleeves and a fitted bodice that flares into a short A-line skirt. Made from lightweight crepe fabric with a back zip closure. The structured puff sleeves create a statement silhouette. Perfect for cocktail parties and date nights.',
    category: 'women',
    subcategory: 'western',
    images: [
      'https://images.unsplash.com/photo-1572804013309-59a88b7e92f1?w=600',
      'https://images.unsplash.com/photo-1595777457583-95e059d581b8?w=600',
    ],
    sizes: ['XS', 'S', 'M', 'L', 'XL'],
    colors: ['Dusty Rose', 'Sage Green', 'Cornflower Blue', 'Black'],
    originalPrice: 3499,
    price: 2099,
    discount: 40,
    stock: 40,
    tags: ['dress', 'mini', 'puff-sleeve', 'women', 'party', 'western', 'trendy', 'cocktail'],
    rating: 4.7,
    reviewCount: 267,
    featured: false,
    isNew: true,
    brand: 'Zara',
    material: '100% Polyester crepe',
    careInstructions: 'Dry clean recommended, hand wash cold if necessary',
  },
  {
    name: 'Wide-Leg Linen Trousers',
    description:
      'Breezy wide-leg trousers made from premium linen for effortless summer style. Features a high-rise waist, elastic back waistband, front pleats, and side pockets. The relaxed fit and breathable linen fabric make these perfect for hot days whether at work or on a casual outing.',
    category: 'women',
    subcategory: 'western',
    images: [
      'https://images.unsplash.com/photo-1572804013309-59a88b7e92f1?w=600',
      'https://images.unsplash.com/photo-1485218126466-34e6392ec754?w=600',
    ],
    sizes: ['XS', 'S', 'M', 'L', 'XL', 'XXL'],
    colors: ['Natural White', 'Sand', 'Slate Blue', 'Terracotta', 'Sage'],
    originalPrice: 2999,
    price: 1799,
    discount: 40,
    stock: 55,
    tags: ['trousers', 'wide-leg', 'linen', 'women', 'summer', 'casual', 'work', 'comfortable'],
    rating: 4.6,
    reviewCount: 203,
    featured: false,
    isNew: true,
    brand: 'Massimo Dutti',
    material: '100% Linen',
    careInstructions: 'Machine wash on gentle cycle 30°C, iron while damp for best results',
  },

  // ─── MEN - WESTERN (additional) ────────────────────────────────────────────
  {
    name: 'Relaxed Fit Polo T-Shirt',
    description:
      'A refined polo t-shirt in a relaxed fit that bridges the gap between casual and smart. Made from premium pique cotton with a classic three-button placket, ribbed collar, and side vents. The versatile design makes it perfect for golf, weekend outings, and smart-casual dress codes.',
    category: 'men',
    subcategory: 'tops',
    images: [
      'https://images.unsplash.com/photo-1617137968427-85924c800a22?w=600',
      'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=600',
    ],
    sizes: ['S', 'M', 'L', 'XL', 'XXL', '3XL'],
    colors: ['White', 'Navy', 'Forest Green', 'Coral', 'Yellow', 'Burgundy'],
    originalPrice: 1999,
    price: 1199,
    discount: 40,
    stock: 80,
    tags: ['polo', 't-shirt', 'men', 'casual', 'golf', 'smart-casual', 'pique', 'summer'],
    rating: 4.5,
    reviewCount: 445,
    featured: false,
    isNew: false,
    brand: 'Lacoste',
    material: '100% Pique Cotton',
    careInstructions: 'Machine wash 40°C, do not tumble dry, iron on reverse',
  },
  {
    name: 'Tailored Blazer in Stretch Fabric',
    description:
      'A sharp, modern blazer crafted from stretch fabric for comfort and flexibility. Features a notched lapel, two-button front, structured shoulders, and functional pockets. The stretch fabric allows full range of motion while maintaining a polished silhouette. Wear to office meetings or evening events.',
    category: 'men',
    subcategory: 'tops',
    images: [
      'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=600',
      'https://images.unsplash.com/photo-1617137968427-85924c800a22?w=600',
    ],
    sizes: ['S', 'M', 'L', 'XL', 'XXL'],
    colors: ['Charcoal', 'Navy', 'Black', 'Light Grey'],
    originalPrice: 6999,
    price: 4199,
    discount: 40,
    stock: 30,
    tags: ['blazer', 'jacket', 'men', 'formal', 'office', 'stretch', 'tailored', 'professional'],
    rating: 4.8,
    reviewCount: 178,
    featured: true,
    isNew: false,
    brand: 'Arrow',
    material: '74% Polyester, 23% Viscose, 3% Elastane',
    careInstructions: 'Dry clean only, press with medium heat',
  },

  // ─── ACCESSORIES - WATCHES ─────────────────────────────────────────────────
  {
    name: "Men's Chronograph Watch",
    description:
      'A bold chronograph watch with a stainless steel case and a comfortable silicone strap. Features a Japanese quartz movement, water resistance up to 50m, luminous hands, and three sub-dials for chronograph function. The sports-inspired design with a clean aesthetic suits every occasion.',
    category: 'accessories',
    subcategory: 'jewelry',
    images: [
      'https://images.unsplash.com/photo-1523275335684-37898b6baf30?w=600',
      'https://images.unsplash.com/photo-1548036328-c9fa89d128fa?w=600',
    ],
    sizes: ['One Size'],
    colors: ['Black/Silver', 'Black/Gold', 'Blue/Silver', 'White/Silver'],
    originalPrice: 4999,
    price: 2999,
    discount: 40,
    stock: 35,
    tags: ['watch', 'chronograph', 'men', 'accessories', 'sports', 'stainless steel'],
    rating: 4.7,
    reviewCount: 256,
    featured: false,
    isNew: true,
    brand: 'Fastrack',
    material: 'Stainless steel case, silicone strap, mineral glass',
    careInstructions: 'Wipe with dry cloth, avoid magnets, service every 2 years',
  },

  // ─── KIDS - WESTERN ────────────────────────────────────────────────────────
  {
    name: "Boys' Denim Jacket",
    description:
      'A cool denim jacket for boys with a classic collar, button front, and chest pockets. Made from mid-weight denim with a slightly distressed wash for a modern look. The comfortable fit allows easy layering over t-shirts and hoodies. A versatile wardrobe staple for kids.',
    category: 'kids',
    subcategory: 'western',
    images: [
      'https://images.unsplash.com/photo-1617137968427-85924c800a22?w=600',
      'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=600',
    ],
    sizes: ['3-4Y', '4-5Y', '5-6Y', '6-7Y', '7-8Y', '8-9Y', '9-10Y', '10-11Y'],
    colors: ['Light Blue', 'Dark Blue', 'Black'],
    originalPrice: 1799,
    price: 1099,
    discount: 39,
    stock: 45,
    tags: ['jacket', 'denim', 'boys', 'kids', 'casual', 'western', 'layering'],
    rating: 4.6,
    reviewCount: 167,
    featured: false,
    isNew: false,
    brand: 'Flying Machine Junior',
    material: '100% Cotton denim',
    careInstructions: 'Machine wash cold, inside out, hang dry',
  },
];

const seedDatabase = async () => {
  try {
    console.log('Connecting to MongoDB...');
    await mongoose.connect(MONGODB_URI, {
      serverSelectionTimeoutMS: 10000,
    });
    console.log('Connected to MongoDB.');

    console.log('Clearing existing products...');
    await Product.deleteMany({});
    console.log('Existing products cleared.');

    console.log(`Inserting ${products.length} products...`);
    const inserted = await Product.insertMany(products);
    console.log(`Successfully inserted ${inserted.length} products.`);

    // Print summary
    const categoryCounts = products.reduce((acc, p) => {
      acc[p.category] = (acc[p.category] || 0) + 1;
      return acc;
    }, {} as Record<string, number>);

    console.log('\nProduct summary by category:');
    Object.entries(categoryCounts).forEach(([category, count]) => {
      console.log(`  ${category}: ${count} products`);
    });

    const featuredCount = products.filter((p) => p.featured).length;
    const newCount = products.filter((p) => p.isNew).length;
    console.log(`\nFeatured products: ${featuredCount}`);
    console.log(`New arrivals: ${newCount}`);
    console.log('\nDatabase seeded successfully!');
  } catch (error) {
    console.error('Error seeding database:', error);
    process.exit(1);
  } finally {
    await mongoose.disconnect();
    console.log('MongoDB disconnected.');
    process.exit(0);
  }
};

seedDatabase();
